//
//  AppDelegate.swift
//  iosApp
//
//  Generated by KMPNotifier Plugin
//

import SwiftUI
import FirebaseCore
import FirebaseMessaging
import UserNotifications
import ComposeApp

class AppDelegate: NSObject, UIApplicationDelegate, UNUserNotificationCenterDelegate, MessagingDelegate {

    func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {

        // Délégué des notifications système pour intercepter foreground/click
        UNUserNotificationCenter.current().delegate = self

        // Délégué Firebase Messaging (token FCM, refresh…)
        Messaging.messaging().delegate = self

        // S'inscrire aux remote notifications (APNs)
        DispatchQueue.main.async {
            UIApplication.shared.registerForRemoteNotifications()
        }
        return true
    }

    // Reçoit le device token APNs -> le passe à FCM
    func application(_ application: UIApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
    }

    // Si l'enregistrement APNs échoue
    func application(_ application: UIApplication,
                     didFailToRegisterForRemoteNotificationsWithError error: Error) {
        print("❌ APNs registration failed: \(error)")
    }

    // Affichage d'une notif en foreground (iOS 10+)
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        // Laisse KMPNotifier traiter le payload data
        let userInfo = notification.request.content.userInfo
        NotifierManager.shared.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)

        // Afficher en foreground (alerte/son/badge)
        completionHandler([.banner, .sound, .badge])
    }

    // Click sur la notification (tap)
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        let userInfo = response.notification.request.content.userInfo

        // Informe KMPNotifier (déclenchera onNotificationClicked côté shared)
        NotifierManager.shared.onApplicationDidReceiveRemoteNotification(userInfo: userInfo)

        completionHandler()
    }

    // Token FCM (utile pour l'envoyer à ton backend)
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        if let token = fcmToken {
            print("🔑 FCM token (iOS): \(token)")
        }
    }
}